[package]
name        = "signatory"
description = "Multi-provider digital signature library with Ed25519 support"
version     = "0.4.1" # Also update html_root_url in lib.rs when bumping this
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://github.com/tendermint/signatory"
repository  = "https://github.com/tendermint/signatory/tree/master"
readme      = "README.md"
categories  = ["authentication", "cryptography", "no-std"]
keywords    = ["crypto", "cryptography", "no_std", "security", "signatures"]

[badges]
circle-ci = { repository = "tendermint/signatory" }

[dependencies]
ed25519-dalek = { version = "0.6", optional = true, default-features = false, features = ["sha2"] }
ring = { version = "0.12", optional = true }
sha2 = { version = "0.7", optional = true }
sodiumoxide = { version = "0.0.16", optional = true }
untrusted = { version = "0.5", optional = true }
yubihsm = { version = "0.7", optional = true }

[dev-dependencies]
criterion = "0.2"

[features]
dalek-provider = ["ed25519-dalek", "sha2", "verifier"]
default = ["dalek-provider"]
nightly = ["ed25519-dalek/nightly"]
std = []
ring-provider = ["ring", "untrusted", "verifier"]
sodiumoxide-provider = ["sodiumoxide", "verifier"]
verifier = []
yubihsm-provider = ["std", "yubihsm"]
yubihsm-mockhsm = ["yubihsm-provider", "yubihsm/mockhsm"]

[package.metadata.docs.rs]
features = ["dalek-provider", "ring-provider", "sodiumoxide-provider", "yubihsm-provider"]
rustc-args = ["-Ctarget-feature=+aes"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[[bench]]
name = "ed25519"
harness = false
