[package]
name        = "signatory"
description = "Multi-provider digital signature library with Ed25519 support"
version     = "0.0.0"
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
categories  = ["cryptography", "no-std"]
keywords    = ["cryptography", "security", "signatures"]
repository  = "https://github.com/tendermint/signatory"
readme      = "README.md"

[dependencies]
ed25519-dalek = { version = "0.6", optional = true, default-features = false, features = ["sha2"] }
sha2 = { version = "0.6", optional = true }

[features]
dalek = ["ed25519-dalek", "sha2"]
default = ["dalek"]
