[package]
name        = "signatory"
description = "Multi-provider elliptic curve digital signature library with ECDSA and Ed25519 support"
version     = "0.8.0" # Also update html_root_url in lib.rs when bumping this
license     = "MIT OR Apache-2.0"
authors     = ["Tony Arcieri <tony@iqlusion.io>"]
homepage    = "https://github.com/tendermint/signatory"
repository  = "https://github.com/tendermint/signatory/tree/master"
readme      = "README.md"
categories  = ["authentication", "cryptography", "no-std"]
keywords    = ["cryptography", "ecdsa", "ed25519", "signing", "signatures"]
autobenches = false

[badges]
circle-ci = { repository = "tendermint/signatory" }

[dependencies]
clear_on_drop = { version = "0.2", optional = true, default-features = false }
digest = { version = "0.7", optional = true, default-features = false }
generic-array = { version = "0.9", optional = true }
rand = { version = "0.5", optional = true }
sha2 = { version = "0.7", optional = true }

[features]
default = ["std", "test-vectors"]
ecdsa = ["generic-array"]
ed25519 = ["clear_on_drop", "rand"]
pkcs8 = ["clear_on_drop"]
std = []
test-vectors = []

[workspace]
members = [
    "providers/signatory-dalek",
    "providers/signatory-ring",
    "providers/signatory-secp256k1",
    "providers/signatory-sodiumoxide",
    "providers/signatory-yubihsm",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1

[package.metadata.docs.rs]
all-features = true
