[package]
name        = "signatory"
description = "Multi-provider digital signature library with Ed25519 support"
version     = "0.3.1" # Also update html_root_url in lib.rs when bumping this
license     = "MIT/Apache-2.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
homepage    = "https://github.com/tendermint/signatory"
repository  = "https://github.com/tendermint/signatory/tree/master"
readme      = "README.md"
categories  = ["cryptography", "no-std"]
keywords    = ["cryptography", "security", "signatures"]

[badges]
circle-ci = { repository = "tendermint/signatory" }

[dependencies]
curve25519-dalek = { version = "= 0.14.0", optional = true, default-features = false }
ed25519-dalek = { version = "= 0.6.0", optional = true, default-features = false, features = ["sha2"] }
failure = { version = "0.1", default-features = false }
failure_derive = { version = "0.1", default-features = false }
sha2 = { version = "0.6", optional = true }
yubihsm = { version = "0.7", optional = true }

[features]
dalek-provider = ["curve25519-dalek", "ed25519-dalek", "sha2"]
default = ["dalek-provider"]
std = ["failure/std", "failure_derive/std"]
yubihsm-provider = ["std", "yubihsm"]
yubihsm-mockhsm = ["yubihsm-provider", "yubihsm/mockhsm"]

[package.metadata.docs.rs]
features = ["dalek-provider", "yubihsm-provider"]
rustc-args = ["-Ctarget-feature=+aes"]
