version: 2

jobs:
  build:
    docker:
      - image: tarcieri/signatory-circleci:201802051857

    steps:
      - checkout
      - restore_cache:
          key: cache-201802051839
      - run:
          name: rustfmt
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
      - run:
          name: build (nightly)
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build
      - run:
          name: build (stable)
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: test (stable)
          command: rustup run stable cargo test
      - save_cache:
          key: cache-201802051839
          paths:
            - "~/.cargo"
            - "./target"
