version: 2

jobs:
  build:
    docker:
      - image: tarcieri/rust-yubihsm-sdk:20180306
    environment:
      - RUSTFLAGS=-C target-feature=+aes
      - CARGO_FEATURES: dalek-provider,yubihsm-mockhsm

    steps:
      - checkout
      - restore_cache:
          key: cache-20180306
      - run:
          name: rustfmt
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
      - run:
          name: clippy
          command: |
            cargo clippy --version
            cargo clippy --verbose --features=$CARGO_FEATURES
      - run:
          name: build (nightly, all features)
          command: |
            # Nightly is the default toolchain
            rustc --version --verbose
            cargo --version --verbose
            cargo build --features=$CARGO_FEATURES
      - run:
          name: test (nightly, all features)
          command: |
            # Nightly is the default toolchain
            rustc --version --verbose
            cargo --version --verbose
            cargo test --features=$CARGO_FEATURES
      - run:
          name: build (stable, default features only)
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build --features=$CARGO_FEATURES
      - run:
          name: test (stable, default features only)
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo test
      - save_cache:
          key: cache-20180306
          paths:
            - "~/.cargo"
            - "./target"
