version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:20180715.0 # bump cache keys when modifying this
    environment:
      # All features except "nightly"
      - CARGO_FEATURES: dalek-provider,ring-provider,secp256k1-provider,sodiumoxide-provider,yubihsm-mockhsm

    steps:
      - checkout
      - restore_cache:
           key: cache-20180715.0 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            cargo +$RUST_NIGHTLY_VERSION fmt --version
            cargo +$RUST_NIGHTLY_VERSION fmt -- --check
      - run:
          name: clippy
          command: |
            cargo +$RUST_NIGHTLY_VERSION clippy --version
            cargo +$RUST_NIGHTLY_VERSION clippy --all-features
      - run:
          name: build (no features)
          command: |
            rustc --version
            cargo --version
            cargo build --benches
      - run:
          name: build (ecdsa feature only)
          command: |
            rustc --version
            cargo --version
            cargo build --benches --features=ecdsa
      - run:
          name: build (ed25519 feature only)
          command: |
            rustc --version
            cargo --version
            cargo build --benches --features=ed25519
      - run:
          name: build (all features except nightly)
          command: |
            rustc --version
            cargo --version
            cargo build --benches --features=$CARGO_FEATURES
      - run:
          name: build (--all-features including nightly)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version
            cargo +$RUST_NIGHTLY_VERSION --version
            cargo +$RUST_NIGHTLY_VERSION build --benches --all --all-features
      - run:
          name: test (all features except nightly)
          command: |
            rustc --version
            cargo --version
            cargo test --features=$CARGO_FEATURES
      - run:
          name: test (--all-features including nightly)
          command: |
            rustup run $RUST_NIGHTLY_VERSION rustc --version
            cargo +$RUST_NIGHTLY_VERSION --version
            cargo +$RUST_NIGHTLY_VERSION test --all-features
      - save_cache:
          key: cache-20180715.0 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
